#local development settings
version: '3'
services:
    nginx:
        volumes:
            - "./src:/app"
            - "./etc/nginx.conf:/etc/nginx/conf.d/default.template"
        expose:
            - "80"
    php:
        #command: /bin/sh -c "crontab -u www-data /usr/crontab && /usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf" #aktivizējam supervisor && cron && queues.
        environment:
            COMPOSER_CACHE_DIR: '/tmp/composer-cache'
        volumes:
            - "./etc/php-local.ini:/usr/local/etc/php/conf.d/php.ini"
            - "./src:/app"
            - "/tmp/composer-cache:/tmp/composer-cache"
            - "./crontab:/usr/crontab"
    adminer:
        image: adminer
        container_name: ${PROJECT}-adminer
        expose:
            - "8080"
        restart: always
    mysql:
        volumes:
            - "/docker-data/${PROJECT}/mysql:/var/lib/mysql"
    #    ports:
        #    - "3306:3306"
