version: '3'
services:
    nginx:
        volumes:
            - "/docker-data/${PROJECT}/uploads:/app/public/uploads"
        expose:
          - '80'
          - '443'
        environment:
            - VIRTUAL_HOST=${VIRTUAL_NAME}.staging.netcore.lv
            - LETSENCRYPT_HOST=${VIRTUAL_NAME}.staging.netcore.lv
            - LETSENCRYPT_EMAIL=developers@netcore.lv
            - VIRTUAL_PORT=80
            - VIRTUAL_PROTO=http
    php:
        environment:
            - COMPOSER_CACHE_DIR=/cache/composer
        volumes:
            - "/var/cache:/cache:rw"
            - "/docker-data/${PROJECT}/storage:/app/storage"
            - "/docker-data/${PROJECT}/uploads:/app/public/uploads"
            - "/docker-data/${PROJECT}/.env:/app/.env"
        links:
            - mysql
    mysql:
        volumes:
            - "/docker-data/${PROJECT}/mysql:/var/lib/mysql"
#        ports:
#            - "3306:3306"