#local development settings
version: '3'
services:
    nginx:
        volumes:
            - "./src:/app:delegated"
            - "./etc/nginx.conf:/etc/nginx/conf.d/default.template"
        expose:
            - "80"
        command: /bin/sh -c "envsubst '$$VIRTUAL_HOST' < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    php:
        environment:
            - COMPOSER_CACHE_DIR=/cache/composer
        volumes:
            - "./etc/php-local.ini:/usr/local/etc/php/conf.d/php.ini"
            - "./src:/app"
            - "${COMPOSER_HOME_DIR}/cache/composer:/cache/composer"
            - "./crontab:/usr/crontab"
        #command: /bin/sh -c "crontab -u www-data /usr/crontab && /usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf" #aktivizējam supervisor && cron && queues.
        links:
            - mysql
    adminer:
        image: adminer
        container_name: ${PROJECT}-adminer
        expose:
            - 8080
        restart: always
    mysql:
        volumes:
            - mysql-volume:/var/lib/mysql
        ports:
            - "3306:3306"
volumes:
    mysql-volume: