version: '3'
services:
    nginx:
        volumes:
            - "./src:/app:delegated"
            - "./etc/nginx.conf:/etc/nginx/conf.d/default.template"
        expose:
            - "80"
        command: /bin/sh -c "envsubst '$$VIRTUAL_HOST' < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    php:
        environment:
            - COMPOSER_CACHE_DIR=/cache/composer
        volumes:
            - "./src:/app"
            - "${COMPOSER_HOME_DIR}/cache/composer:/cache/composer"
        links:
            - mysql
    mysql:
        volumes:
            - mysql-volume:/var/lib/mysql
        ports:
            - "3287:3306"
volumes:
    mysql-volume: